name: Install cypress

on:
  # to allow to wait for a cypress install to proceed in another workflow
  workflow_call:

jobs:
  install-cypress:
    runs-on: ubuntu-24.04
    container:
      image: cypress/browsers:node-20.18.0-chrome-130.0.6723.69-1-ff-131.0.3-edge-130.0.2849.52-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          runTests: false
          build: npm run build

      - name: Save dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          if-no-files-found: error
          path: dist
 