name: E2E Tests in PR

on:
  push:

jobs:
  # install-cypress:
  #   uses: ./.github/workflows/.reusable-install-cypress.yml

  e2e-tests:
    runs-on: ubuntu-24.04
    # needs:
    #   - install-cypress
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start OpenNebula
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            make install --always-make
            
            make start --always-make --ignore-errors

            sleep 20

            curl http://localhost:2616
          push: never

      - name: Check OpenNebula health
        run: |
          docker ps -a
          CID=$(docker ps -q)
          docker exec "$CID" curl -I http://localhost:2616
          docker port "$CID" || true
          docker inspect "$CID" --format '{{json .NetworkSettings.Ports}}'
          curl http://localhost:2616

      - name: Cypress run e2e tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: "http://localhost:2616"
          browser: electron

      - name: Upload videos of tests failed
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: |
            cypress/videos/*.mp4
            cypress/screenshots/**/*.png